Add extractor skeleton and .proto files
src-d/berserker pull request #1
Opened 2017-06-30 10:29 UTC by ajnavarro

2017-06-30 11:33 UTC, smola requested changes
Add some tests.

2017-06-30 11:33 UTC, smola commented on extractor/server/server.go
> +	"github.com/src-d/berserker/extractor"
Use proper import groups.

2017-06-30 11:33 UTC, smola commented on extractor/server/server.go
> +	// TODO parametrize
You might want to open an issue instead of a TODO comment.

2017-06-30 11:33 UTC, smola commented on extractor/server/server.go
> +	fmt.Println("STARTED")
Use `logrus`.

2017-06-30 11:33 UTC, smola commented on extractor/server/server.go
> +	panic(grpcServer.Serve(lis))
If I recall correctly, `Serve` always exits with error (because in absence of error it runs forever). So don't use panic, just log the error instead.

2017-06-30 11:33 UTC, smola commented on extractor/model.go
> +	Hash     []byte
Is this file hash or commit hash? If it's commit hash, call it `Commit` or `CommitHash`?

2017-06-30 11:39 UTC, ajnavarro commented on extractor/model.go
> +	Hash     []byte
It's the file hash

2017-06-30 11:40 UTC, ajnavarro commented on extractor/server/server.go
> +	fmt.Println("STARTED")
will we use logrus instead of log15?

2017-06-30 13:15 UTC, ajnavarro commented on extractor/server/server.go
> +	// TODO parametrize
https://github.com/src-d/berserker/issues/2

2017-06-30 13:23 UTC, smola commented on extractor/server/server.go
> +	fmt.Println("STARTED")
No, sorry, I was confused. We didn't really decided to switch. So keep log15.

2017-06-30 14:24 UTC, bzz commented
Looks good to me.

The only wish is - in readme explain a bit about how it's going to be used and which are the "source of truth" files, so people with previous .proto experience do not get confused.

2017-06-30 14:34 UTC, ajnavarro commented
@bzz This is well explained into `proteus` project, isn't it? Should we repeat here the same as is explained in proteus?

2017-07-03 06:33 UTC, bzz commented
Imagine a new user who wants to build and run Berserker.

Does Proteus project mention an architecture of data analysis pipeline? Like which parts communicate with what using what kind of interfaces and where are they defined? 

It would be nice to have a link to Proteus project as well, when touching up on it's role in this project.

I do not think this blocks merging this PR, but it would be super-nice to have a few works about architecture from the beginning of the project.

2017-07-04 07:14 UTC, bzz commented
@smola 
> Add some tests.
What kind of test do you mean? This PR is about `.proto` files only, and is not expected to have much except for that as all it just represents the interface between upcoming Golang and Java work.

@ajnavarro Looks good to me, modulo the comments above.

Shall we merge it now and proceed with Scala/Golang parts?

2017-07-04 07:59 UTC, smola approved these changes

2017-07-04 07:59 UTC, merged